modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"

[[mods]]
modId="travel_anchors"
version="${file.jarVersion}"
displayName="Travel Anchors"
credits="MelanX and noeppi_noeppi"
authors="CastCrafter"
description='''
Adds a staff of travelling and a travel anchor to teleport around the world.
'''

[[dependencies.travel_anchors]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.travel_anchors]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.travel_anchors]]
    modId="libx"
    mandatory=true
    versionRange="[1.16.3-1.0.29,)"
    ordering="NONE"
    side="BOTH"