modLoader="javafml"
loaderVersion="[37,)"
license="Apache License 2.0"

[[mods]]
modId="travel_anchors"
version="${file.jarVersion}"
displayName="Travel Anchors"
credits="MelanX and noeppi_noeppi"
authors="CastCrafter"
description='''
Adds a staff of travelling and a travel anchor to teleport around the world.
'''

[[dependencies.travel_anchors]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.travel_anchors]]
    modId="forge"
    mandatory=true
    versionRange="[1.17.1-37.0.13,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.travel_anchors]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,)"
    ordering="NONE"
    side="BOTH"
