modLoader="javafml"
loaderVersion="[41,)"
license="Apache License 2.0"

[[mods]]
modId="travelanchors"
version="${file.jarVersion}"
displayName="Travel Anchors"
displayURL="https://www.curseforge.com/minecraft/mc-mods/travel-anchors"
updateJSONURL="https://assets.melanx.de/updates/travel-anchors.json"
credits="MelanX and noeppi_noeppi"
authors="CastCrafter"
description='''
Adds a staff of travelling and a travel anchor to teleport around the world.
'''

[[dependencies.travelanchors]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.98,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.travelanchors]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.travelanchors]]
    modId="libx"
    mandatory=true
    versionRange="[1.19-4.0.4,)"
    ordering="NONE"
    side="BOTH"
