modLoader="javafml"
loaderVersion="[39,)"
license="Apache License 2.0"

[[mods]]
modId="travel_anchors"
version="${file.jarVersion}"
displayName="Travel Anchors"
displayURL="https://www.curseforge.com/minecraft/mc-mods/travel-anchors"
updateJSONURL="https://assets.melanx.de/updates/travel-anchors.json"
credits="MelanX and noeppi_noeppi"
authors="CastCrafter"
description='''
Adds a staff of travelling and a travel anchor to teleport around the world.
'''

[[dependencies.travel_anchors]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.travel_anchors]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.travel_anchors]]
    modId="libx"
    mandatory=true
    versionRange="[1.18.2-3.2.2,)"
    ordering="NONE"
    side="BOTH"
